import { setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/navigation';
import TopicPage, { TopicSteps, topicStyles as s } from '@/components/pages/TopicPage';
import EngineeringDrawing from '@/components/visuals/EngineeringDrawing';
import { LANDSCAPE_PHASES, LANDSCAPE_SNAPSHOT } from '@/lib/data/engineering-landscape';
import { APPLICATION_PAGES } from '@/lib/data/application-pages';
import { pageMetadata } from '@/lib/seo/metadata';

const PATH = '/ki-produktentwicklung';
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  return pageMetadata(PATH, locale, locale === 'en' ? 'AI in technical product development | AImation' : 'KI in der technischen Produktentwicklung | AImation', locale === 'en' ? 'Practical AI workflows for engineering teams: requirements, validation, reports and knowledge. Explore a use-case catalogue, working demonstrations and training.' : 'KI für Entwicklungsteams: Anforderungen prüfen, Berichte vorbereiten und Wissen auffindbar machen. Mit Use-Case-Landkarte, echten Anwendungsdemos und Schulung.');
}
export default async function Page({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);
  const en = locale === 'en';
  const lang = en ? 'en' : 'de';
  const home = en ? '/en' : '/';
  const faqs = en ? [
    { question: 'Where can AI help in technical product development?', answer: 'Potential tasks include structuring requirements, finding previous decisions and drafting reports from approved data. Suitability depends on available sources, the review process and measurable benefit for your team.' },
    { question: `Are the ${LANDSCAPE_SNAPSHOT.cases} use cases completed customer projects?`, answer: 'No. Development Landscape is a catalogue of potential applications in engineering and adjacent functions. The separate application videos show prototypes or demonstrations, not customer references.' },
    { question: 'Does AI approve designs or test results?', answer: 'No. The workflows described here retain technical review and approval by the responsible specialists. AI suggestions and drafts must remain traceable to their sources.' },
  ] : [
    { question: 'Wo hilft KI in der technischen Produktentwicklung?', answer: 'Mögliche Aufgaben sind das Strukturieren von Anforderungen, das Auffinden früherer Entscheidungen und Berichtsentwürfe aus freigegebenen Daten. Ob das passt, hängt von Quellen, Prüfprozess und messbarem Nutzen für Ihr Team ab.' },
    { question: `Sind die ${LANDSCAPE_SNAPSHOT.cases} Use Cases abgeschlossene Kundenprojekte?`, answer: 'Nein. Die Development Landscape ist ein Katalog möglicher Anwendungen in der Entwicklung und angrenzenden Bereichen. Die separaten Anwendungsvideos zeigen Prototypen oder Demonstrationen, keine Kundenreferenzen.' },
    { question: 'Gibt die KI Konstruktionen oder Prüfergebnisse frei?', answer: 'Nein. In den beschriebenen Abläufen bleiben fachliche Prüfung und Freigabe bei den verantwortlichen Fachpersonen. KI-Hinweise und Entwürfe müssen auf ihre Quellen zurückführbar bleiben.' },
  ];
  const qkt = en ? [['Quality', 'Find omissions before approval.', 'Check requirements, evidence and recurring defects against defined criteria.'], ['Cost', 'Spend less time preparing the review.', 'Prepare Excel data, meeting decisions and report drafts together. Count checking and correction time too.'], ['Timing', 'See dependencies sooner.', 'Make missing information, conflicting dates and capacity bottlenecks visible before they hold up the next step.']] : [['Qualität', 'Lücken vor der Freigabe erkennen.', 'Anforderungen, Nachweise und Wiederholfehler anhand festgelegter Kriterien prüfen.'], ['Kosten', 'Weniger Aufwand vor dem Review.', 'Excel-Daten, Meetingbeschlüsse und Berichtsentwürfe gemeinsam vorbereiten. Kontrolle und Korrektur zählen mit.'], ['Timing', 'Abhängigkeiten früher sehen.', 'Fehlende Angaben, widersprüchliche Termine und Kapazitätsengpässe erkennen, bevor sie den nächsten Schritt aufhalten.']];
  return <TopicPage locale={locale} path={PATH} label={en ? 'AI in product development' : 'KI in der Produktentwicklung'} title={en ? 'Give engineering teams' : 'Damit Entwicklungsteams wieder'} accent={en ? 'time to develop.' : 'zum Entwickeln kommen.'}
    intro={en ? 'AI is useful where it removes a specific burden: checking a specification, finding a decision or preparing a review. We start inside your engineering workflow and check what actually helps.' : 'KI wird dort interessant, wo sie eine konkrete Aufgabe erleichtert: ein Lastenheft prüfen, eine Entscheidung wiederfinden oder ein Review vorbereiten. Wir gehen in Ihre Entwicklung und prüfen, was dort wirklich hilft.'}
    visual={<EngineeringDrawing/>} facts={[en ? '20+ years of engineering experience' : '20+ Jahre Engineering-Erfahrung', `${LANDSCAPE_SNAPSHOT.cases} ${en ? 'catalogue entries' : 'Katalogeinträge'}`, en ? 'Consulting · training · implementation' : 'Beratung · Schulung · Umsetzung']}
    faqs={faqs} cta={en ? 'Discuss your engineering task' : 'Entwicklungsaufgabe besprechen'}
    related={[{ href: '/ki-schulungen-mittelstand', label: en ? 'Training and learning sample' : 'Schulung und Lernprobe' }, { href: '/use-cases/excel-powerpoint-berichte', label: en ? 'Replace Excel with dashboards and apps' : 'Excel durch Dashboards und Apps ablösen' }]}>
    <div className="engineering-wrap">
      <section className={s.section} id="einblick"><p className={s.eyebrow}>{en ? 'Quality / cost / timing' : 'Qualität / Kosten / Timing'}</p><h2>{en ? 'Your priorities set the starting point.' : 'Ihre Engpässe bestimmen den Einstieg.'}</h2><div className={s.qkt}>{qkt.map(([label, title, text], i) => <article key={label}><span className={s.eyebrow}>0{i + 1} / {label}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className={s.note}>{en ? 'A faster draft is not enough. A pilot must include review time, errors and rework in the comparison.' : 'Ein schnellerer Entwurf allein reicht nicht. Ein Pilot muss Prüfzeit, Fehler und Nacharbeit im Vergleich mit erfassen.'}</p></section>
      <section className={s.section}><div className={s.split}><div><p className={s.eyebrow}>Development Landscape</p><h2>{en ? 'A map of tasks worth examining.' : 'Eine Landkarte für die Aufgaben dahinter.'}</h2></div><div><p>{en ? `The catalogue contains ${LANDSCAPE_SNAPSHOT.cases} potential applications in ${LANDSCAPE_SNAPSHOT.areas} areas, mainly technical product development and adjacent functions. The following six phases show selected examples.` : `Der Katalog umfasst ${LANDSCAPE_SNAPSHOT.cases} mögliche Anwendungen in ${LANDSCAPE_SNAPSHOT.areas} Bereichen, überwiegend technische Produktentwicklung und angrenzende Aufgaben. Die folgenden sechs Phasen zeigen ausgewählte Beispiele.`}</p><p className={s.note}>{en ? 'Catalogue snapshot' : 'Katalogstand'}: {LANDSCAPE_SNAPSHOT.date}. {en ? 'Ideas for assessment, not a list of delivered projects.' : 'Ansätze zur Prüfung, keine Liste umgesetzter Kundenprojekte.'}</p></div></div>
        <div className={s.catalogue}>{LANDSCAPE_PHASES.map(phase => <article key={phase.id}><p className={s.eyebrow}>{phase[lang]}</p><h3>{phase.cases[0][lang][0]}</h3><p>{phase.cases[0][lang][1]} {phase.cases[0][lang][2]}</p><a className="engineering-text-link" href={`${home}#use-case-${phase.cases[0].id}`}>{en ? 'Explore the example' : 'Beispiel durchspielen'} →</a></article>)}</div>
        <a href={`${home}#use-cases`} className="engineering-text-link">{en ? 'Open the interactive landscape and its video' : 'Interaktive Landkarte und Video öffnen'} ↗</a>
      </section>
      <section className={`${s.section} ${s.split}`}><div><p className={s.eyebrow}>{en ? 'Built by AImation' : 'Von AImation gebaut'}</p><h2>{en ? 'See what the tools actually do.' : 'Ansehen, was die Werkzeuge tatsächlich tun.'}</h2><p>{en ? 'Three recordings show the current demonstration states. Each detail page explains the workflow, data requirements and limits.' : 'Drei Aufnahmen zeigen die aktuellen Demonstrationsstände. Jede Detailseite erklärt Ablauf, Datenbedarf und Grenzen.'}</p></div><div className={s.links}>{Object.values(APPLICATION_PAGES).map(app => <Link key={app.path} href={app.path}>{app[lang].label}<span aria-hidden="true">↗</span></Link>)}<a href={`${home}#selbst-gebaut`}>{en ? 'Also explore 5Why, FEM and the ideas agents' : 'Auch 5Why, FEM und die Ideen-Agenten erkunden'}<span aria-hidden="true">↗</span></a></div></section>
      <section className={`${s.section} ${s.split}`}><div><p className={s.eyebrow}>{en ? 'A scoped start' : 'Ein abgegrenzter Anfang'}</p><h2>{en ? 'One workflow. Clear test criteria.' : 'Ein Ablauf. Klare Prüfkriterien.'}</h2><p>{en ? 'The first step is a task your team can compare before and after. We agree the sources, reviewers and success criteria before building.' : 'Der erste Schritt ist eine Aufgabe, die Ihr Team vorher und nachher vergleichen kann. Quellen, Prüfer und Erfolgskriterien legen wir vor dem Bau fest.'}</p></div><TopicSteps steps={en ? [['Identify the task', 'Choose a recurring bottleneck. Check available data, access and responsibilities.'], ['Test the workflow', 'Build a scoped pilot. Compare results, review effort and rework with the current process.'], ['Prepare the team', 'Train the people who use and approve the output. Agree maintenance, access and operations before rollout.']] : [['Aufgabe eingrenzen', 'Einen wiederkehrenden Engpass auswählen. Verfügbare Daten, Zugriffe und Verantwortlichkeiten prüfen.'], ['Ablauf testen', 'Einen abgegrenzten Pilot bauen. Ergebnis, Prüfaufwand und Nacharbeit mit dem bisherigen Prozess vergleichen.'], ['Team vorbereiten', 'Die Personen schulen, die Ergebnisse nutzen und freigeben. Pflege, Zugriffe und Betrieb vor der Einführung klären.']]}/></section>
    </div>
  </TopicPage>;
}
