import { setRequestLocale } from 'next-intl/server';
import TopicPage, { TopicSteps, topicStyles as s } from '@/components/pages/TopicPage';
import LearningSample from '@/components/visuals/LearningSample';
import { pageMetadata } from '@/lib/seo/metadata';

const PATH = '/schulungen/microsoft-365-copilot';
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  return pageMetadata(PATH, locale, locale === 'en' ? 'Microsoft 365 Copilot training for teams | AImation' : 'Microsoft 365 Copilot Schulung für Teams | AImation', locale === 'en' ? 'Practical Copilot training: prompts, meeting follow-up, content and data analysis. Nine learning modules, an interactive sample and an in-house format agreed for your team.' : 'Copilot-Schulung mit Aufgaben aus Ihrem Alltag: Prompts, Meeting-Nacharbeit, Inhalte und Datenanalyse. Neun Lernmodule, interaktive Lernprobe und abgestimmtes Inhouse-Format.');
}
export default async function Page({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);
  const en = locale === 'en';
  const modules = en ? ['AI fundamentals for Copilot newcomers', 'Copilot introduction and the prompt formula', 'Summarising and rewriting', 'Working with transcripts and building agents', 'Planning and organising', 'Searching and learning', 'Creating and translating content', 'Data analysis', 'Meta-prompting, review and next steps'] : ['KI-Grundlagen für Copilot-Einsteiger', 'Copilot kennenlernen und Prompts aufbauen', 'Zusammenfassen und Umschreiben', 'Transkripte auswerten und eigene Agenten bauen', 'Planen und Organisieren', 'Suchen und Lernen', 'Inhalte erstellen und übersetzen', 'Datenanalyse', 'Meta-Prompting, Zusammenfassung und Ausblick'];
  const examples = en ? [['Excel', 'Ask precise questions about an approved dataset. Check calculations against their source.'], ['PowerPoint', 'Prepare a presentation outline from approved content. Review facts and structure before sharing.'], ['Meetings', 'Extract decisions and actions from approved notes. Do not invent missing owners.']] : [['Excel', 'Präzise Fragen an einen freigegebenen Datenbestand stellen. Berechnungen an der Quelle kontrollieren.'], ['PowerPoint', 'Aus freigegebenen Inhalten einen Präsentationsaufbau vorbereiten. Fakten und Struktur vor dem Teilen prüfen.'], ['Meetings', 'Beschlüsse und Aufgaben aus freigegebenen Notizen herausarbeiten. Fehlende Verantwortliche nicht erfinden.']];
  const faqs = en ? [{ question: 'Do we need Microsoft 365 Copilot licences?', answer: 'That depends on the exercises and the functions to be used. Before the workshop, we check accounts, licences, enabled features and access to sample data with your organisation. Microsoft licences are not included in the training.' }, { question: 'Do all nine modules fit into one training day?', answer: 'The nine modules describe the available learning series, not a promised one-day agenda. We select topics, duration and exercises to fit your team’s experience and goals.' }, { question: 'Will we use confidential company data?', answer: 'Only data approved for the agreed environment should be used. Where approval is missing, we use sample data. Data access and rules for use are settled before the exercises.' }, { question: 'Is this an official Microsoft certification course?', answer: 'No Microsoft certification is promised. AImation offers practical team training assembled from its own learning materials.' }] : [{ question: 'Brauchen wir Microsoft-365-Copilot-Lizenzen?', answer: 'Das hängt von den Übungen und den verwendeten Funktionen ab. Vor dem Workshop prüfen wir mit Ihrem Unternehmen Konten, Lizenzen, freigeschaltete Funktionen und den Zugriff auf Übungsdaten. Microsoft-Lizenzen sind nicht Teil der Schulung.' }, { question: 'Passen alle neun Module in einen Schulungstag?', answer: 'Die neun Module beschreiben die vorhandene Lernreihe, keine zugesagte Tagesagenda. Themen, Dauer und Übungen wählen wir passend zu Vorwissen und Lernziel Ihres Teams.' }, { question: 'Arbeiten wir mit vertraulichen Unternehmensdaten?', answer: 'Verwendet werden nur Daten, die für die vereinbarte Umgebung freigegeben sind. Fehlt diese Freigabe, arbeiten wir mit Beispieldaten. Zugriffe und Nutzungsregeln klären wir vor den Übungen.' }, { question: 'Ist das eine offizielle Microsoft-Zertifizierung?', answer: 'Eine Microsoft-Zertifizierung wird nicht zugesagt. AImation bietet eine praktische Teamschulung auf Basis eigener Lernmaterialien.' }];
  return <TopicPage locale={locale} path={PATH} label={en ? 'Microsoft 365 Copilot training' : 'Microsoft 365 Copilot Schulung'} parent={{ href: '/ki-schulungen-mittelstand', label: en ? 'AI training' : 'KI-Schulungen' }}
    title={en ? 'Put Copilot to work.' : 'Copilot an der eigenen Arbeit lernen.'} accent={en ? 'On your own tasks.' : 'Mit prüfbaren Ergebnissen.'}
    intro={en ? 'Your team practises on tasks from its working day: preparing meeting follow-up, checking data and structuring presentations. We choose the exercises around your tools, experience and approved data.' : 'Ihr Team übt an Aufgaben aus dem Arbeitsalltag: Meetings nachbereiten, Daten prüfen und Präsentationen strukturieren. Die Übungen passen zu Ihren Werkzeugen, Ihrem Vorwissen und den freigegebenen Daten.'}
    facts={[en ? '9 modules in the learning series' : '9 Module in der Lernreihe', en ? 'In-house format by agreement' : 'Inhouse-Format nach Abstimmung', en ? 'Includes expert review of results' : 'Ergebnisse fachlich prüfen']}
    visual={<div className={s.plate}><p className={s.eyebrow}>{en ? 'Your working day / the practice material' : 'Ihr Arbeitsalltag / der Übungsstoff'}</p><h2>{en ? 'From an instruction to a result you can check.' : 'Vom Arbeitsauftrag zum prüfbaren Ergebnis.'}</h2><div className={s.plateRows}>{examples.map(([title, text], i) => <div key={title}><span>0{i + 1}</span><div><strong>{title}</strong><p>{text}</p></div></div>)}</div></div>}
    faqs={faqs} cta={en ? 'Discuss your team’s training' : 'Schulung fürs Team besprechen'} related={[{ href: '/ki-schulungen-mittelstand', label: en ? 'All six learning series' : 'Alle sechs Lernreihen' }, { href: '/use-cases/excel-powerpoint-berichte', label: en ? 'The reporting workflow' : 'Der Berichtsprozess im Detail' }, { href: '/ki-produktentwicklung', label: en ? 'AI in product development' : 'KI in der Produktentwicklung' }]}>
    <div id="einblick" className={s.anchor}><LearningSample/></div>
    <div className="engineering-wrap">
      <section className={s.section} id="kurs-copilot"><div className={s.split}><div><p className={s.eyebrow}>{en ? 'From the existing learning materials' : 'Aus den vorhandenen Lernmaterialien'}</p><h2>{en ? 'Nine modules. Your selection.' : 'Neun Module. Ihr Zuschnitt.'}</h2></div><p>{en ? 'We assemble the workshop from the available learning series. Not every team needs every module. Access to supporting materials, duration and scope are agreed for your format.' : 'Aus der vorhandenen Lernreihe stellen wir den Workshop zusammen. Nicht jedes Team braucht jedes Modul. Zugang zu begleitenden Materialien, Dauer und Umfang vereinbaren wir für Ihr Format.'}</p></div><ol className={s.curriculum}>{modules.map(module => <li key={module}>{module}</li>)}</ol></section>
      <section className={`${s.section} ${s.split}`}><div><p className={s.eyebrow}>{en ? 'Before the workshop' : 'Vor dem Workshop'}</p><h2>{en ? 'Set up the exercise properly.' : 'Die Übung beginnt bei den Voraussetzungen.'}</h2><p>{en ? 'Copilot capabilities depend on licences, accounts and settings in your organisation. We check which exercises your environment supports before finalising the agenda. No confidential data goes into an unapproved tool.' : 'Copilot-Funktionen hängen von Lizenzen, Konten und Einstellungen Ihres Unternehmens ab. Vor der Agenda prüfen wir, welche Übungen Ihre Umgebung trägt. Vertrauliche Daten gehören nicht in ein ungeprüftes Werkzeug.'}</p><a className="engineering-text-link mt-6" href="https://learn.microsoft.com/en-us/microsoft-365/copilot/microsoft-365-copilot-minimum-requirements">{en ? 'Microsoft: current requirements' : 'Microsoft: aktuelle Voraussetzungen'} ↗</a></div><TopicSteps steps={en ? [['Choose the task', 'Bring two or three recurring tasks. Together we define what participants should be able to do afterwards.'], ['Prepare access', 'Agree accounts, licences, sample data and rules for use. Check permissions before the workshop.'], ['Practise and check', 'Formulate instructions, compare outputs with sources and improve them. Leave with a workflow your team understands.']] : [['Aufgabe auswählen', 'Bringen Sie zwei oder drei wiederkehrende Aufgaben mit. Gemeinsam legen wir fest, was die Teilnehmer danach können sollen.'], ['Zugänge vorbereiten', 'Konten, Lizenzen, Übungsdaten und Nutzungsregeln abstimmen. Berechtigungen vor dem Workshop prüfen.'], ['Anwenden und prüfen', 'Arbeitsaufträge formulieren, Ergebnisse mit Quellen vergleichen und nachbessern. Am Ende steht ein Ablauf, den Ihr Team versteht.']]}/></section>
    </div>
  </TopicPage>;
}
