'use client';
import { useRef, useState, type KeyboardEvent } from 'react';
import styles from './ReportingWorkbench.module.css';

// An authored walkthrough with fictional input, not an AI inference or live tool.
export default function ReportingWorkbench({ en }: { en: boolean }) {
  const [active, setActive] = useState(2);
  const [assigned, setAssigned] = useState(false);
  const refs = useRef<(HTMLButtonElement | null)[]>([]);
  const tabs = en ? ['Sources', 'Checks', 'Dashboard', 'App', 'History', 'Export'] : ['Daten', 'Prüfung', 'Dashboard', 'App', 'Historie', 'Export'];
  function navigate(event: KeyboardEvent<HTMLButtonElement>, index: number) {
    const next = event.key === 'ArrowRight' ? (index + 1) % tabs.length : event.key === 'ArrowLeft' ? (index + tabs.length - 1) % tabs.length : event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : null;
    if (next === null) return;
    event.preventDefault(); setActive(next); refs.current[next]?.focus();
  }
  return <section className={styles.workbench} aria-labelledby="reporting-example-title">
    <div className={styles.heading}><div><p className="technical-label">{en ? 'Interactive target workflow / fictional data' : 'Interaktiver Zielablauf / fiktive Daten'}</p><h2 id="reporting-example-title">{en ? 'See the status. Work in the app.' : 'Den Stand sehen. In der App handeln.'}</h2></div><span>AP-017 / REV. 01</span></div>
    <div className={styles.tabs} role="tablist" aria-label={en ? 'From Excel to an application' : 'Von Excel zur Anwendung'}>{tabs.map((label, i) => <button ref={element => { refs.current[i] = element; }} key={label} type="button" role="tab" id={`report-tab-${i}`} aria-controls="report-panel" aria-selected={active === i} tabIndex={active === i ? 0 : -1} onClick={() => setActive(i)} onKeyDown={event => navigate(event, i)}><span>0{i + 1}</span>{label}</button>)}</div>
    <div id="report-panel" role="tabpanel" aria-labelledby={`report-tab-${active}`} tabIndex={0} className={styles.panel}>
      {active === 0 && <div className={styles.split}><div><h3>{en ? 'Initial import / Excel test planning' : 'Erstübernahme / Excel-Versuchsplanung'}</h3><dl><div><dt>{en ? 'Work package' : 'Arbeitspaket'}</dt><dd>AP-017</dd></div><div><dt>{en ? 'Planned date' : 'Plantermin'}</dt><dd>14.10.2026</dd></div><div><dt>{en ? 'Current forecast' : 'Aktuelle Prognose'}</dt><dd>16.10.2026</dd></div></dl></div><div><h3>{en ? 'Meeting note / N-03' : 'Meetingnotiz / N-03'}</h3><blockquote>{en ? '“Test fixture arrives later. Check the effect on the review date.”' : '„Prüfvorrichtung kommt später. Auswirkung auf den Reviewtermin prüfen.“'}</blockquote><p>{en ? 'No owner was recorded. The target workflow maintains new updates in the app, without keeping a parallel Excel list.' : 'Kein Verantwortlicher notiert. Im Zielablauf werden neue Stände direkt in der App gepflegt, ohne parallele Excel-Liste.'}</p></div></div>}
      {active === 1 && <div className={styles.split}><div><p className="technical-label">{en ? 'Fixed calculation rule' : 'Feste Rechenregel'}</p><h3>{en ? '2 calendar days later' : '2 Kalendertage später'}</h3><p>16.10.2026 − 14.10.2026 = 2 {en ? 'days' : 'Tage'}</p><p>{en ? 'Calculated from the dates, not estimated by AI. Whether the review is affected cannot be derived from these inputs alone.' : 'Aus den Terminen berechnet, nicht von KI geschätzt. Ob das Review betroffen ist, lässt sich daraus allein nicht ableiten.'}</p></div><div className={styles.flag}><p className="technical-label">{en ? 'Open for review' : 'Offen für die Prüfung'}</p><h3>{en ? 'Owner missing' : 'Verantwortlicher fehlt'}</h3><p>{en ? 'Note N-03 names no owner. The field stays open. The project lead needs to assign the follow-up and check the dependency.' : 'Notiz N-03 nennt keinen Verantwortlichen. Das Feld bleibt offen. Die Projektleitung muss die Rückfrage zuordnen und die Abhängigkeit prüfen.'}</p></div></div>}
      {active === 2 && <div className={styles.split}><div><p className="technical-label">{en ? 'Dashboard / work package AP-017' : 'Dashboard / Arbeitspaket AP-017'}</p><div className={styles.metrics}><div><span>{en ? 'Schedule deviation' : 'Terminabweichung'}</span><strong>+2</strong><span>{en ? 'calendar days' : 'Kalendertage'}</span></div><div><span>{en ? 'Review impact' : 'Auswirkung aufs Review'}</span><strong>{en ? 'Open' : 'Offen'}</strong><span>{en ? 'Expert assessment pending' : 'Fachliche Prüfung ausstehend'}</span></div></div><p>{en ? 'Plan: 14 October · Forecast: 16 October 2026. Source: AP-017, revision 01.' : 'Plan: 14. Oktober · Prognose: 16. Oktober 2026. Quelle: AP-017, Revision 01.'}</p><button type="button" className={styles.action} onClick={() => { setActive(3); refs.current[3]?.focus(); }}>{en ? 'Open record in the app' : 'Vorgang in der App öffnen'} →</button></div><div><h3>{en ? 'The review uses shared data.' : 'Das Review nutzt den gemeinsamen Datenstand.'}</h3><p>{en ? 'Dashboards and BI show results directly from the data foundation. There is no need to rebuild this view in PowerPoint each week.' : 'Dashboards und BI zeigen Ergebnisse direkt aus der Datenbasis. Diese Ansicht muss nicht jede Woche in PowerPoint nachgebaut werden.'}</p><p>{en ? 'An AI explanation could describe the deviation with source references. The +2 comes from a fixed calculation. AI does not decide whether the review must move.' : 'Eine KI-Erläuterung kann die Abweichung mit Quellenbezug beschreiben. Die +2 stammen aus einer festen Berechnung. Ob das Review verschoben werden muss, entscheidet die KI nicht.'}</p></div></div>}
      {active === 3 && <div className={styles.split}><div><p className="technical-label">{en ? 'Application / task AP-017' : 'Anwendung / Aufgabe AP-017'}</p><h3>{en ? 'Check the effect on the review.' : 'Auswirkung aufs Review prüfen.'}</h3><dl><div><dt>{en ? 'Source' : 'Quelle'}</dt><dd>N-03 / AP-017</dd></div><div><dt>{en ? 'Owner' : 'Zuständigkeit'}</dt><dd aria-live="polite">{assigned ? (en ? 'Project lead (demo)' : 'Projektleitung (Demo)') : (en ? 'Unassigned' : 'Noch offen')}</dd></div><div><dt>Status</dt><dd>{en ? 'Assessment pending' : 'Prüfung ausstehend'}</dd></div></dl><button type="button" className={styles.action} onClick={() => setAssigned(value => !value)}>{assigned ? (en ? 'Reset demo assignment' : 'Demo-Zuordnung zurücksetzen') : (en ? 'Assign project lead in demo' : 'In der Demo Projektleitung zuordnen')}</button></div><div><h3>{en ? 'Update the record where the work happens.' : 'Den Vorgang dort pflegen, wo die Arbeit stattfindet.'}</h3><p>{en ? 'Inputs, ownership and approvals belong in the app. AI can propose tasks from notes; a person checks and accepts them. Defined rules validate required fields and control permitted transitions.' : 'Eingaben, Zuständigkeiten und Freigaben gehören in die App. KI kann Aufgaben aus Notizen vorschlagen; eine Person prüft und übernimmt sie. Feste Regeln prüfen Pflichtfelder und steuern zulässige Statuswechsel.'}</p><p>{en ? 'Try the assignment. It changes only this example in your current browser session. No message is sent and no database is connected.' : 'Probieren Sie die Zuordnung aus. Sie ändert nur dieses Beispiel in der geöffneten Seite. Es wird keine Nachricht versendet und keine Datenbank angebunden.'}</p></div></div>}
      {active === 4 && <div className={styles.split}><div><h3>{en ? 'Keep both versions.' : 'Beide Stände bleiben erhalten.'}</h3><dl><div><dt>REV. 00 / {en ? 'Plan' : 'Planstand'}</dt><dd>AP-017 · 14.10.2026</dd></div><div><dt>REV. 01 / {en ? 'Forecast' : 'Prognose'}</dt><dd>AP-017 · 16.10.2026</dd></div><div><dt>{en ? 'Source of change' : 'Änderungsquelle'}</dt><dd>{en ? 'Excel / AP-017 + note N-03' : 'Excel / AP-017 + Notiz N-03'}</dd></div><div><dt>{en ? 'Assignment in this demo' : 'Zuordnung in dieser Demo'}</dt><dd>{assigned ? (en ? 'Unassigned → project lead' : 'Offen → Projektleitung') : (en ? 'No change' : 'Keine Änderung')}</dd></div></dl></div><div><h3>{en ? 'A database needs versioning rules.' : 'Eine Datenbank braucht Regeln für die Historie.'}</h3><p>{en ? 'For your implementation, we define which data versions, changes and approvals are recorded, with timestamps and responsible users. The new forecast must not overwrite the original plan.' : 'Für Ihre Umsetzung legen wir fest, welche Datenstände, Änderungen und Freigaben mit Zeitpunkt und Verantwortlichen protokolliert werden. Die neue Prognose darf den ursprünglichen Plan nicht überschreiben.'}</p><p>{en ? 'These records are illustrative. This example does not connect to a database or persist changes.' : 'Die Einträge dienen der Veranschaulichung. Dieses Beispiel verbindet keine Datenbank und speichert Änderungen nicht dauerhaft.'}</p></div></div>}
      {active === 5 && <div className={styles.split}><div className={styles.draft}><p className="technical-label">{en ? 'Optional PowerPoint export / draft' : 'Optionaler PowerPoint-Export / Entwurf'}</p><h3>{en ? 'Test AP-017' : 'Versuch AP-017'}</h3><p>{en ? 'Current forecast: 16 October, two calendar days after plan. The effect on the review remains to be assessed.' : 'Aktuelle Prognose: 16. Oktober, zwei Kalendertage nach Plan. Die Auswirkung auf das Review ist noch zu bewerten.'}</p><small>{en ? 'Sources: AP-017 / revision 01; note N-03' : 'Quellen: AP-017 / Revision 01; Notiz N-03'}</small></div><div><h3>{en ? 'Only when a recipient needs slides.' : 'Nur wenn ein Empfänger noch Folien braucht.'}</h3><p>{en ? 'Day-to-day work stays in the dashboard and app. A checked snapshot can be exported for external recipients. It does not become a second place to maintain data.' : 'Die tägliche Arbeit bleibt im Dashboard und in der App. Für externe Empfänger kann ein geprüfter Stand exportiert werden. Er wird nicht zur zweiten Stelle für Datenpflege.'}</p><p>{en ? 'This prepared example does not generate or export an actual presentation.' : 'Dieses vorbereitete Beispiel erzeugt oder exportiert keine echte Präsentation.'}</p></div></div>}
    </div>
    <p className={styles.caption}>{en ? 'Click through the steps. A scripted illustration with no AI request and no data upload.' : 'Klicken Sie durch die Schritte. Vorbereitete Veranschaulichung ohne KI-Abfrage und ohne Datenübertragung.'}</p>
  </section>;
}
